Actionbar:
  Message: "&cHealth - {health}/{max_health}      &bMana - {mana}/{max_mana}"
  Interval: 10 # Half a second between refresh

Intelligence:
  Regen:
    Amount: 1.05 #This is 5% of max
    Interval: 60 #This is 3 seconds

Abilities:
  Teleport:
    description:
      - "&eItem Ability: &aTeleport"
      - "&2‣ &aRight Click &7to teleport forward &a10"
      - "&7blocks."
      - "&8This ability costs 25 mana and has no cooldown"
    mana-cost: 25
    cooldown: 0
  SoulSteal:
    description:
      - "&eItem Ability: &aSoul Steal"
      - "&2‣ &aRight Click &7to activate a timer, in which"
      - "&7you gain &c+5 Force &7for every kill within &a10"
      - "&7seconds. Capped at &c+500 Force&7. Timer restarts"
      - "&7on kill."
      - "&8This ability costs 0 mana and has a 60s cooldown."
    mana-cost: 0
    cooldown: 60
  InstantFire:
    description:
      - "&ePassive Ability: &aInstant Fire"
      - "&2‣ &7This bow instantly fires a fully charged"
      - "&7arrow upon right clicking."
    mana-cost: 0
    cooldown: 0
  RapidHeal:
    description:
      - "&eItem Ability: &aRapid Heal"
      - "&2‣ &aRight Click &7to instantly heal yourself for"
      - "&c150 &7health"
      - "&8This ability costs 50 mana and has no cooldown."
    mana-cost: 50
    cooldown: 0
  MagmaMountain:
    description:
      - "&eItem Ability: &aMagma Mountain"
      - "&2‣ &aRight Click &7to send a wave of hot magma down"
      - "&7on your enemy, which will deal &b{damage} &7damage."
      - "&8This ability costs 100 mana and has a 3s cooldown"
    mana-cost: 100
    cooldown: 0
  BulkUp:
    description:
      - "&eItem Ability: &aBulk Up"
      - "&2‣ &aRight Click &7to bulk up your body, gaining"
      - "&a+150 Defense &7and &c+100 Force &7for 30s."
      - "&8This ability costs 70 mana and has a 45s cooldown"
    mana-cost: 70
    cooldown: 45
  AssassinStrike:
    description:
      - "&eItem Ability: &aAssassin's Strike"
      - "&2‣ &aRight Click &7to merge into the shadows, teleporting"
      - "&7to and freezing in place the nearest enemy."
      - "&8This ability costs 130 mana and has a 10s cooldown"
    mana-cost: 130
    cooldown: 10
  SpiritWave:
    description:
      - "&eItem Ability: &aSpirit Wave"
      - "&2‣ &aRight Click &7to send an orb of spirit energy"
      - "&7forward, which will deal &b{damage} &7damage to all"
      - "&7nearby mobs."
      - "&8This ability costs 90 mana and has no cooldown"
    mana-cost: 90
    cooldown: 0
  WitherGlide:
    description:
      - "&eItem Ability: &aWither Glide"
      - "&2‣ &aRight Click &7to spawn and ride a wither forward 15"
      - "&7blocks, dealing &b{damage} &7damage to any mob caught in the"
      - "&7Wither's explosion (&c3 &7block range)"
      - "&8This ability costs 150 mana and has a 5s cooldown."
    mana-cost: 150
    cooldown: 5s
  EnderManiac:
    description:
      - "&eItem Ability: &aEnder Maniac"
      - "&2‣ &aRight Click &7to gain &c{damage} &7damage and"
      - "&b{agility} &7agility against Endermen for 2 minutes."
      - "&7The amount of damage and agility increases as you"
      - "&7kill more Endermen using this sword."
      - "&8This ability costs 100 mana and has a 150s cooldown."
    mana-cost: 100
    cooldown: 150